# Generated by Django 4.2.5 on 2023-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_id', models.CharField(max_length=10)),
                ('Plate_number', models.CharField(max_length=10)),
                ('Make', models.CharField(max_length=15)),
                ('Model', models.CharField(max_length=15)),
                ('Capacity', models.CharField(max_length=100)),
                ('Transmission', models.CharField(choices=[('A', 'AUTOMATIC'), ('M', 'MANUAL')], max_length=2)),
                ('Price_per_day', models.CharField(max_length=4)),
                ('Status', models.CharField(max_length=20)),
                ('Driver', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DRIVER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_id', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=2)),
                ('License_number', models.CharField(max_length=60)),
                ('Contact', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
