# Generated by Django 4.2.5 on 2023-10-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIRING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hire_date', models.DateField()),
                ('Customer', models.CharField(max_length=20)),
                ('car', models.CharField(max_length=20)),
                ('Service_type', models.CharField(choices=[('S', 'SELF DRIVE'), ('D', 'DRIVEN')], max_length=2)),
                ('Number_of_days', models.IntegerField()),
                ('Amount_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_date', models.DateField()),
                ('Hire', models.CharField(max_length=20)),
                ('Amount_paid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='Car_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Driver_id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='Gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2),
        ),
    ]
